# Site
title:              Kasper
bio:                ''
description:        "of code, games and things"
locale:             utf-8
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kaspersauramo.me" # the base hostname & protocol for your site

defaults:
  -
    scope:
        path: ""
        type: "posts"
    values:
        permalink: "/blog/:title/"
        layout: "post"
        author: "Kasper"

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Github Pages settings
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge


# Comments
disqus_shortname:   kaspersauramo

# Social
twitter:            kmschme
github:             schme

# personal
location:           Helsinki, Finland
email:              mail@kaspersauramo.me

# Gems
plugins:
  - github-pages
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
